In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[
    [1,2,3],
             ]])
a2

array([[[1, 2, 3]]])

In [4]:
a1.shape


(3,)

In [5]:
a1.ndim

1

In [6]:
a2=np.array([[1,2,3],
             [4,5,6]
            ])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#create a dataframe ffrom numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
a3=np.array([
    [[[1],2,3],
     [4,5,6]
    ]
])
a3.ndim

/var/folders/mp/hk05nn2x3x5b_s2b069qfsgc0000gn/T/ipykernel_30681/3066234944.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a3=np.array([


3

In [10]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
np.random.seed(seed=10)
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0]])

In [16]:
random_array_2=np.random.random((3,5))
random_array_2

array([[0.81123778, 0.49815322, 0.36273743, 0.87858452, 0.16354632],
       [0.54858183, 0.77579319, 0.79319598, 0.59148774, 0.58845281],
       [0.46498755, 0.55265161, 0.48963299, 0.40752211, 0.89619473]])