In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[
    [1,2,3],
             ]])
a2

array([[[1, 2, 3]]])

In [4]:
a1.shape


(3,)

In [5]:
a1.ndim

1

In [6]:
a2=np.array([[1,2,3],
             [4,5,6]
            ])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#create a dataframe ffrom numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [28]:
a3=np.array([
    [
     [[1,7],2,3],
     [4,5,6]
    ]
])
a3.ndim

/var/folders/mp/hk05nn2x3x5b_s2b069qfsgc0000gn/T/ipykernel_30681/1128490844.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a3=np.array([


3

In [10]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
np.random.seed(seed=10)
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0]])

In [16]:
random_array_2=np.random.random((3,5))
random_array_2

array([[0.81123778, 0.49815322, 0.36273743, 0.87858452, 0.16354632],
       [0.54858183, 0.77579319, 0.79319598, 0.59148774, 0.58845281],
       [0.46498755, 0.55265161, 0.48963299, 0.40752211, 0.89619473]])

## Viewing arrays and matrices

In [23]:
np.unique(a1)

array([1, 2, 3])

In [24]:
a1[0]

1

In [25]:
a2[0]

array([1, 2, 3])

In [26]:
a2[1]

array([4, 5, 6])

In [27]:
a3[0]

array([[list([1]), 2, 3],
       [4, 5, 6]], dtype=object)

In [29]:
a4=np.random.randint(0,10,size=(2,3,4,5))
a4

array([[[[4, 6, 8, 1, 8],
         [4, 1, 3, 6, 5],
         [3, 9, 6, 9, 1],
         [9, 4, 2, 6, 7]],

        [[8, 8, 9, 2, 0],
         [6, 7, 8, 1, 7],
         [1, 4, 0, 8, 5],
         [4, 7, 8, 8, 2]],

        [[6, 2, 8, 8, 6],
         [6, 5, 6, 0, 0],
         [6, 9, 1, 8, 9],
         [1, 2, 8, 9, 9]]],


       [[[5, 0, 2, 7, 3],
         [0, 4, 2, 0, 3],
         [3, 1, 2, 5, 9],
         [0, 1, 0, 1, 9]],

        [[0, 9, 2, 1, 1],
         [0, 0, 5, 9, 0],
         [4, 6, 6, 0, 2],
         [3, 3, 2, 6, 0]],

        [[5, 1, 3, 6, 5],
         [5, 1, 8, 0, 5],
         [9, 8, 5, 7, 8],
         [5, 8, 9, 9, 1]]]])

In [30]:
a4[:2,:2,:2,:2]

array([[[[4, 6],
         [4, 1]],

        [[8, 8],
         [6, 7]]],


       [[[5, 0],
         [0, 4]],

        [[0, 9],
         [0, 0]]]])

In [33]:
a4[:1,:,:,:]

array([[[[4, 6, 8, 1, 8],
         [4, 1, 3, 6, 5],
         [3, 9, 6, 9, 1],
         [9, 4, 2, 6, 7]],

        [[8, 8, 9, 2, 0],
         [6, 7, 8, 1, 7],
         [1, 4, 0, 8, 5],
         [4, 7, 8, 8, 2]],

        [[6, 2, 8, 8, 6],
         [6, 5, 6, 0, 0],
         [6, 9, 1, 8, 9],
         [1, 2, 8, 9, 9]]]])

# MANIPULATING ARRays

In [34]:
a1


array([1, 2, 3])

In [36]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [37]:
a1+ones


array([2., 3., 4.])

In [38]:
a1

array([1, 2, 3])

In [39]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a1*a2


array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [41]:
massive_array=np.random.random(100000)

In [42]:
massive_array.size

100000

In [43]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

5.93 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.1 µs ± 231 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [44]:
np.var(a2)

2.9166666666666665

In [45]:
np.sum(a2)

21

In [47]:
a2.shape

(2, 3)

In [48]:
a3.shape

(1, 2, 3)

In [49]:
a2*a3

array([[[list([1, 7]), 4, 9],
        [16, 25, 36]]], dtype=object)

In [52]:
a2=a2.reshape(1,2,3)

In [53]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [54]:
a2.shape

(1, 2, 3)

In [55]:
a2*a3

array([[[list([1, 7]), 4, 9],
        [16, 25, 36]]], dtype=object)

In [56]:
a2.shape

(1, 2, 3)

In [57]:
a2.T.shape

(3, 2, 1)

In [58]:
np.random.seed(0)

mat1=np.random.randint(0,10,size=(5,3))
mat2=np.random.randint(0,10,size=(5,3))


In [59]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [60]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [63]:
mat2=mat2.T

In [64]:
mat3=np.dot(mat1,mat2)

In [65]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [66]:
mat2=mat2.T

In [67]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [68]:
mat2=mat2.reshape(3,5)

In [69]:
mat2

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [71]:
np.dot(mat1,mat2)

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

# Excersie nut butter

In [72]:
np.random.seed(0)
import pandas as pd
sales_array=np.random.randint(0,20,size=(5,3))
sales=pd.DataFrame(sales_array,index=["mon","tues","wed","thu","fri"],
                  columns=["almond butter","peanut butter","cashew butter"])

In [73]:
sales

almond butter  peanut butter  cashew butter
mon              12             15              0
tues              3              3              7
wed               9             19             18
thu               4              6             12
fri               1              6              7

In [75]:
prices_array=np.random.randint(0,15,size=(1,3))
prices=pd.DataFrame(prices_array,index=["Price"],columns=["peanut butter","almon butter","cashew butter"])

In [76]:
prices

peanut butter  almon butter  cashew butter
Price              7            14              8

In [85]:
total_sales=prices_array.dot(sales_array.T)

In [86]:
total_sales

array([[294, 119, 473, 208, 147]])

In [87]:
prices

peanut butter  almon butter  cashew butter
Price              7            14              8

In [91]:
sales

almond butter  peanut butter  cashew butter  Total amount
mon              12             15              0           294
tues              3              3              7           119
wed               9             19             18           473
thu               4              6             12           208
fri               1              6              7           147

In [89]:
sales["Total amount"]=total_sales.T

In [90]:
total_sales

array([[294, 119, 473, 208, 147]])